language: node_js
node_js:
- '7.6'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang

before_install:
- export CXX="g++-4.8"
- export CC="gcc-4.8"

before_script:
- npm install

script:
- npm test

after_success: bash ./bin/deploy.sh

env:
  global:
  - GIT_USER: Travis CI
  - GIT_EMAIL: miya0001@users.noreply.github.com
  - GH_REF: github.com/wakayama-hacker/wmap.git
  - secure: "PzYw9UHgw5CyGLlTZAC8S+l04d8IpNVCnvGLtjvYW4J4En9CDfPhA/GPgwaia5zGLd2VrKqoo7yaqGAoRttsk93TsuGoaW/aGQs8Pmy9EDa/pUoMUn4p4x+llfrLWj/53cKCTtzCGZkU0eqkKrEcZOkMKCSHTd0oxZXPZk0yFfqzKBYWBYfTiTepyYWGofqiyXiId+6vQ2ZOZLiCGYwuc7mgu6TBxNhF92QpD6OVdrMkhw98Az/Xt65bpT9f+PGMqkTwS4oVgkalezGd+E6HRWzlf64B3bKeEO2gbPF7ckTNTWxD7yZ6RGU+kQm+c3FF7Uodqhev6c5fNAE4OmsMb+rg6V6OXyeY4Vfl+AGkrpiqPHno4MOFgtQMMljgYNg/yTINi6U0DrgbrvoouosFTffpY1YaqjItJxEvvOZVaRC35R0PVt51myLQP7f2blaQyjY/O93swpXJ8g3Uwx9s88488zEgV8zumNPFGUgqdXB6AB5lrqS49oU40YnT2WnBsRbb6cHdkpl97wgi0j6gmOPHSO3eu5DciRHz9p18D9ecqR4iZDtTcTOpdvx6hwSf8jMvFnT4BiK1gdfZ/kPJRv+FVUX/sjB9705OedbF0frXIym+ycfHKLhKUt/RAbUnqo3VFwnyIRQerKkgVJ4DodbA9tgTEsXE0qZ4zVrN/nI="
